@SessionAuthentication_HostAddress = http://localhost:5041

GET {{SessionAuthentication_HostAddress}}/todos/
Accept: application/json

###

GET {{SessionAuthentication_HostAddress}}/todos/1
Accept: application/json

###
